{
 "title": "Weather Plus",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "🔥 High-Temp Alert",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ALERTS{alertname=\"HighTemperature\"}",
     "legendFormat": "Alert"
    }
   ]
  },
  {
   "title": "⚠️ Consumer Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ALERTS{alertname=\"ConsumerDown\"}",
     "legendFormat": "Alert"
    }
   ]
  },
  {
   "title": "RabbitMQ Queue Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "weather:queue_lag", "legendFormat": "Mensajes sin consumir" }
   ]
  },
  {
   "title": "Ingesta vs Errores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(weather_inserted_rows[5m])",
     "legendFormat": "Inserted/sec"
    },
    { "expr": "rate(weather_invalid_msg[5m])", "legendFormat": "Invalid/sec" }
   ]
  }
 ]
}